from scrapy import cmdline
# cmdline.execute("scrapy crawl tencent_news_spider -o tencent.csv".split())
# cmdline.execute("scrapy crawl netease_news_spider -o netease.csv".split())
# cmdline.execute("scrapy crawl sohu_news_spider -o sohu11_13.csv".split())
# cmdline.execute("scrapy crawl sina_news_spider -o sina.csv".split())
# cmdline.execute("scrapy crawl xinhua_news_spider -o xinhua.csv".split())
# cmdline.execute("scrapy crawl ifeng_news_spider -o ifeng.csv".split())
# cmdline.execute("scrapy crawl jndsb_news_spider -o jndsb.csv".split())
# cmdline.execute("scrapy crawl jxcbw_news_spider -o jxcbw.csv".split())
cmdline.execute("scrapy crawl cctv_news_spider -o cctv.csv".split())